### PR TITLE
GmAPD Updates

### PR DESCRIPTION
**Pull request by kdamkjer**
Draft enhancements to support GmAPD LiDAR. Addresses Issue #35.

### CODE REVIEW

**Comment by hobu** [comment]
After looking over these changes, my only suggestion is that the "aggregate" bit flag not only correspond to GmAPD systems, and it could also just as easily apply to dense imagery situations. I don't think we need to say anything about algorithms or consensus models on the description of the flag.

**Comment by rapidlasso** [comment]
Looks like the main specification document has changed too much since that pull request was made and now needs manual tweaking to be merged. Maybe someone neutral should volunteer. Please keep the language system neutral.

It occurred to me that if any system needs "special mention" it should be the SPL system because their "single shot of many beamlets" could actually benefit from special consideration whereas GML is just another point cloud derived from multiple observations similar to SfM / dense-matching ... (-:

**Comment by esilvia** [comment]
I should have time tomorrow morning to clear up the merge conflicts from the structural changes I've been doing on the draft. Thanks for your patience while we iron out the final kinks from the GitHub transition.

**Comment by esilvia** [comment]
I managed to resolve the merge conflicts WRT the source code reorganization and pushed the updates to @kdamkjer's branch. With those corrections this pull request looks good to me.

I have a couple questions about the wording that came up during my review, but that won't stop this pull request. I refreshed the issue branch and we can continue the conversation about details on #35.

**Pull request merged**
