### PR TITLE
Resolves #35 - Improve support for new technologies

### LINKED ISSUE #35: Extend/adapt LAS to support new technologies
Harris has expressed concern that LAS doesn't adequately support Geiger-Mode (GM) lidar. Is there a way to enhance/revise LAS to support GM lidar?

### PR DESCRIPTION
**Pull request by esilvia**
This is probably the single most significant change for R14. Summary:

- Added "Aggregate" Global Encoding bit.
- Added language to support technologies beyond linear-mode lidar scanners.
    - Particular emphasis on Harris-style Geiger-mode Lidar and Structure-from-Motion (SfM) point clouds
    - Clarified and renamed "Synthetic Return Numbers" Global Encoding bit.
    - Clarified Synthetic point classification flag.
    - Clarified validity of zero-value PointSourceID.
    - Unified Return Number & Number of Returns descriptions between PDRFs 0-5 and 6-10.
    - Clarified Scan Direction & Edge of Flight Line flags for non-rotational systems.
- Further clarified relationship between FileSourceID and PointSourceID for #59.
- Clarified PDRF 0-5 as the "legacy" point formats.

This completely, finally resolves #35. The final PDF for this can be found here: https://s3.amazonaws.com/asprs-las/LAS-specification-141e42dd11b5abb267dd06c8cf088294e63d3fda.pdf

### CODE REVIEW

**Comment by abellgithub** [comment]
This needs to be accompanied by a change in the minor version.  The current spec says that bit 5 shall be 0.  This PR is incompatible with that requirement and software won't know what to do with the `Aggregate Global Encoding` flag otherwise.

**Comment by lgraham-geocue** [comment]
Any bit changes to the specification must be at least a minor version tick.  We could consider 1.4.1 (a third digit of revision) though I am not a fan of these….

Lewis Graham
GeoCue Group Inc.
9668 Madison Blvd., Suite 202
Madison, AL 35758 USA
256-461-8289
www.geocue.com<http://www.geocue.com>
Software tools for LIDAR &  Drone Mapping
Bespoke Enterprise Workflow Solutions
Drone Mapping Services
Technical Consulting

**Comment by hobu** [comment]
> Any bit changes to the specification must be at least a minor version tick.  We could consider 1.4.1 (a third digit of revision) though I am not a fan of these….

1.4.1 vs. 1.5 would cause software churn. We don't even have a PATCH/REVISION number anywhere. Let's not do that.

Can the authors proposing the modification make the case that this particular change DOES NOT require an increment to the minor version?

**Comment by lgraham-geocue** [comment]
Let’s stay more focused on not breaking LAS 1.4.

You cannot drive any change in expected behavior of file read/write software without changing the version number.  For example, let’s not entertain kludges such as reading some spare field or VLR to figure out how to interpret bits of the file.  Just bite the bullet and increment the minor version number.

A version, if nothing else, is supposed to mean stability.

Lewis Graham
GeoCue Group Inc.
9668 Madison Blvd., Suite 202
Madison, AL 35758 USA
256-461-8289
www.geocue.com<http://www.geocue.com>
Software tools for LIDAR &  Drone Mapping
Bespoke Enterprise Workflow Solutions
Drone Mapping Services
Technical Consulting

**Comment by abellgithub** [comment]
I disagree.  The bit indicates whether the data has the property `Aggregate Global Encoding`.  What's the point if one can't know that a file has this property, which one won't be able to know?  If the bit is set to one, then the property applies, but if it's not set...?  Furthermore, it wouldn't be improper for a LAS 1.4 reader to report an error if it found this bit set.

#1 is different because it removed functionality.  (I'm not wanting to reopen old discussions, but removing those datatypes was pointless -- conforming files may already exist with those datatypes).  It should have required a version update as well.

Changing the specification in any way that changes data interpretation should be accompanied by a at least a minor version change.  Clarifications to existing behavior/interpretation are appropriate for doc revisions.

What's the resistance to bumping the minor version?

**Comment by lgraham-geocue** [comment]
You cannot change bit meaning without a version bump.  This breaks validators - a bad thing.

What is the resistance to doing this the right way?

Sent from my iPad

On Dec 12, 2018, at 14:26, Evon Silvia <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree this is on the razor's edge for differentiating between a minor version vs. revision.

The reason I believe it doesn't break binary compatibility boils down to the fact that the byte in which the bit lives still gets read and written the same way as before. It's still one byte, so software that ignores it completely – i.e., all existing software – won't suffer any ill effects. Existing software can still read and write a compliant LAS 1.4 file. This wouldn't be true if, for example, we added another byte to the end of the header or swapped the order of two fields.

The same concept applies to deprecating or adding new classifications, which we've previously agreed fits within a Revision.

Honestly the only practical change it makes will be in how validators interpret what's "valid" for the LAS file. Normally null scan angles or GPS times would be "invalid", but if the Aggregate flag is set they might decide to let it by with a warning.

Tagging Kristian and Josh in case they want to lean in. @kdamkjer<https://github.com/kdamkjer> @jdnimetz<https://github.com/jdnimetz>

**Comment by kdamkjer** [comment]
I apologize in advance for the length of this reply, but I think we’ve touched on an important distinction between Revision and Version and wanted to make sure I fully weighed the options.

I believe that Evon addresses the primary conditions for Revision vs. Version in his LWG collaboration presentation: https://www.youtube.com/watch?v=Waj_YPRJByQ&feature=youtu.be&t=726

My understanding of the current arguments are:

  1.  Since the byte structure of the file is not changing, a Revision may be appropriate. All changes clarify or revise existing fields. Unused bits in Global Encoding are most likely ignored by existing software (except for validators).
  2.  However, the proposed change to the Global Encoding field may negatively impact existing software. Specifically because:
     *   Currently bits 5:15 “Must be set to zero”
     *   LAS validators checking for this condition will flag for new 1.4 products until they are updated to accommodate the R14 specification
     *   Similarly, LAS validators checking for non-nulled required fields will flag for the same reason
     *   There is no mechanism for software vendors to detect when the change in interpretation is applicable. That is, invalid files under R13 may suddenly become valid with an improperly set Aggregate bit. Validators will fail to flag this condition and other software may misinterpret/misrepresent attribution as a result. Specifically, attributes that were required and missing may be overlooked if Aggregate bit is set.
  3.  The last condition described above will still apply if the version is bumped to 1.5. However, validators will be able to detect faults for files claiming to be LAS 1.4.
  4.  We’ve previously decided that changes to the Classification tables could be handled in Revisions and Global Encoding bits appear to be similar. Specifically:
     *   Classes “Reserved for ASPRS Definition” should not appear in any products
     *   LAS Validators can check for this condition
     *   However, classes added to the ASPRS reserved classes will cause a similar problem as changes to Global Encoding bits for LAS validators that perform this check.
     *   PDRFs 6-10 mitigate this some by providing an expanded classification field and a large range of user definable classes. Thus allowing users to make their own classes without invalidating their files.

I would add the following arguments:

  1.  Requiring the version bump may cause existing software to reject loading data produced under the new specification until it is updated to recognize the new minor version.
  2.  However, the same could be true if software requires files to pass validation prior to loading.
  3.  I believe the former to be more likely than the latter. That is, most software I am familiar with will make a best effort to load data according to the marked version when it is recognized. However, if an unrecognized version is encountered, it will make no such attempt. This will, in turn, delay adoption and acceptance of data that would be otherwise usable immediately.
Evon also gives reasons for resisting a minor version bump in his presentation. I believe the strongest reason he gives would be the timeline for acceptance:

  1.  Revisions require just a 2 week review period and no ASPRS Board approval
  2.  Versions require 60 day public comment period and final approval by ASPRS Board

Finally, I think there is also a hope that changes incorporated into revisions may be adopted faster than changes incorporated into new versions. This could happen, in theory, because specifications would not have to be updated to accept delivery in newer formats. Unfortunately, if formats are specified down to the revision (e.g., as in USGS LBS 1.3), then this is not possible. However, as previously discussed, there is no mechanism to check for adherence to a revision.

Implications:
If we require a version bump, it will take longer for the specification to be accepted. There is also a very real possibility that software will refuse to load products with a higher version than 1.4, even though they probably could since the formats are byte-compatible. We will also set a precedent that all future changes to Global Encoding will require a version bump, even if the new set bit(s) serve only to clarify or re-interpret existing fields.

I personally believe that changing the Global Encoding should require a version bump when it fundamentally impacts the interpretation and loading of the file (GPS Time Type and WKT probably fall in this category). However, if it serves to primarily clarify and inform interpretation of fields then I think a Revision is appropriate (Synthetic Return Number is probably in this category). I personally feel that the Aggregate bit is a case more similar to Synthetic Return Numbering than WKT and would lean toward Revision over Version because of where the weight of potential harm lies.

Sincerely,

Kristian L. Damkjer
Manager, Software Engineering, Geospatial Software
SPACE AND INTELLIGENCE SYSTEMS / HARRIS CORPORATION
Office: +1-321-984-5773 / Mobile: +1-321-890-4198

**Comment by esilvia** [comment]
The resistance to creating LAS 1.5 for what constitutes a relatively small change is the 7+ years it's taken for software to implement LAS 1.4. I'm trying to avoid going through that again unless it's absolutely necessary.

I'm not convinced that LAS 1.4 is incapable of validly storing SfM and GML data, so I don't think creating LAS 1.5 is necessary simply to add a flag to support these technologies.

So far we have two objections to doing this as a revision because of the Aggregate bit. If that's the only sticking point, and we come to consensus that that's definitely an issue, personally I think the way forward is to rewrite the sections such that the global encoding bit isn't required - that is, we add language to each attribute to describe exceptions specific to certain technologies. It's already written that way to some extent, and frankly I always liked this approach better than adding a Global Encoding bit.

**Comment by esilvia** [comment]
@lgraham-geocue I just saw your updated comments. Perhaps it would help if you could clarify how, exactly, adding a Global Encoding bit actually breaks existing software? As a test I manually set the 5th Global Encoding bit and ran it through LAStools, TerraScan, and my own software, without issue.

**Comment by abellgithub** [comment]
Why not define a VLR to indicate this new property? That wouldn't break the
existing spec. And it provides more information: if the VLR exists, it
could indicate whether or not there is aggregate global encoding.  If the
VLR doesn't exist, you know nothing about the aggregate global encoding
(status quo).

**Comment by lgraham-geocue** [comment]
Very simple.
Software has no way of distinguishing the revision of a version.  If I find this bit set to 1 it is a violation of prior revisions but not the new revision.  You simply cannot break bits without a way to distinguish the revisions.  The revision system in LAS was always intended to allow:
The addition of reserved VLRs
Clarification of the specification.

If this just absolutely has to go in without a version bump, just add a reserved VLR.  You can then add the bit definition with the next version bump.  This is simple and does not violate the “don’t break the bits” rule.  Anyone who needs this bit has to modify their code.  They can just look for the VLR.

Lewis


Lewis Graham
GeoCue Group Inc.
9668 Madison Blvd., Suite 202
Madison, AL 35758 USA
256-461-8289
www.geocue.com<http://www.geocue.com>
Software tools for LIDAR &  Drone Mapping
Bespoke Enterprise Workflow Solutions
Drone Mapping Services
Technical Consulting

**Comment by rapidlasso** [comment]
All pro and con arguments have been said. I could go either way. I have the strong suspicion tgat no LAS implementation really takes those (global encoding) bits all that serious anyways, so in practice the issue is probably negligible, but from a strict "let's do it like a respectable standardization committee" point of view a minor increment may be warranted. That said, I think the minor increment will cause much much much  more disruption in practice than it could possibly prevents bad thing from happening (which bad things, for example ... ?).

**Comment by esilvia** [comment]
> Very simple. Software has no way of distinguishing the revision of a version. If I find this bit set to 1 it is a violation of prior revisions but not the new revision.

Thanks for responding Lewis! Why is it important to know that the file is in violation of the previous revisions?

**Comment by esilvia** [comment]
Point taken.

What if we were to omit the Aggregate Global Encoding bit altogether and simply modify the point attribute descriptions such that they explicitly address the new technologies? This may result in some attributes no longer being flagged as Required in the attribute tables.

I like this approach because it aligns with the spirit of the LAS specification, which is to provide a technology- and vendor-agnostic point cloud format. I didn't like that our proposal created a precedent to mandate different flavors of LAS files based on the underlying technology such that each flavor must be interpreted differently, so this improves on that.

This approach, of course, will cause some false positives in validators not set up to ingest LAS files from certain technologies, but that will likely be true in any case because the whole point here is to provide guidance on what a valid LAS file from those technologies should look like. 

Regarding the proposal to use a VLR instead, I appreciate the creative alternative but I don't think it'll work. It would have to be optional by necessity, and there's no flag like the WKT Global Encoding bit to indicate it _should_ be there so it's likely to be stripped by the first software package that touches it. 

At this point I don't remember why we thought a Global Encoding bit was even necessary. I'll see if I can revise the PR later this week once I get a delivery finished.

**Comment by rapidlasso** [comment]
I think this "aggregate bit" would mainly be useful for the (in-official) [LASvalidator](https://github.com/LASvalidator/lasvalidate) that would then not fail LAS/LAZ files because certain fields (such as scan angles) being all zero.

**Comment by abellgithub** [comment]
@esilvia: I don't understand your point WRT the VLR vs. relabeling a bit in the header.

**Comment by esilvia** [comment]
Thanks everyone for your input. You've convinced me a that adding a Global Encoding bit would require advancing the version number. However, I disagree with the characterization of LAS 1.5 being the "right way" to support the new technologies. 

Advancing the LAS version number to 1.5 would imply that 1.4 was unable to store data produced by these technologies, which I think is untrue. **If we're going to advance a LAS version number to support these technologies anyway, the obvious solution is to add a PDRF that cuts out the inapplicable fields** rather than invalidating them. I'd rather not do this because I'd like vendors to think critically about how they might populate the required fields with useful information, which is what we're doing now, rather than setting a very low bar for a minimally compliant LAS 1.4 file.

# VLR alternative

@abellgithub: Regarding the VLR proposal, @kdamkjer phrased it better than I did:

> I feel very strongly that creating a new reserved VLR to serve the same function as the Aggregate bit just to avoid the version bump is a bad idea. [...] The primary problem is that software vendors would have to always check for the presence of the VLR because they aren’t flagged to its existence and the VLR may change the interpretation and valid population of attributes. Validators won’t know when they need to start looking for the VLR because there is no version bump. They can’t blindly ignore the VLR because it affects validation of files. 

I suppose there's no harm in adding the optional VLR, but in my opinion this is a moot point in light of the following...

# The Path Forward

Because it doesn't affect the file structure at all. the Global Encoding bit/VLR seems to only be relevant for the sake of validation. The Synthetic Return Numbers Global Encoding bit serves a similar function and is widely ignored, and I don't see any reason to believe that the Aggregate Global Encoding bit would suffer the same fate, making its addition pointless. 

Therefore, the better solution is to revise 1.4 to provide guidance on how these "Required" fields should be populated when not applicable. That's what I've done in the latest revision of the PR.

But what about validation? I'd recommend that tools like the popular and incredibly useful @rapidlasso LASvalidator can provide controls for the user to manually disable checking for specific issues such as all-zero scan angles or uniform scan directions. These toggles already exist e.g. for omitting warnings about missing the required CRS VLRs, and it shouldn't be difficult to encapsulate a group of these toggles into a single flag e.g. `-aggregate`.

Everyone's feedback on the latest PR is most welcome. @kdamkjer @lgraham-geocue @rapidlasso @abellgithub 

- PDF for this PR here: https://s3.amazonaws.com/asprs-las/LAS-specification-8b5d56525d269f2d14700cdae2ea54d8bb973c9b.pdf
- Changes in latest commit: https://github.com/ASPRSorg/LAS/commit/8b5d56525d269f2d14700cdae2ea54d8bb973c9b
- Overall changes for this pull request: https://github.com/ASPRSorg/LAS/pull/75/files

**Comment by rapidlasso** [comment]
For the LASvalidator either the bit or the flag is fine (implementation-wise). An '-aggregate' flag will make it the responsibility of the user to know about the difference between "single-measurement LiDAR points" and "aggregate-measured point clouds". But that may be better anyways.

**Comment by esilvia** [comment]
> For the LASvalidator either the bit or the flag is fine (implementation-wise). An '-aggregate' flag will make it the responsibility of the user to know about the difference between "single-measurement LiDAR points" and "aggregate-measured point clouds". But that may be better anyways.

Perhaps if LASvalidate issues a warning about these related fields it can link to the relevant section of the specification? We could also adapt Kristian's presentation on Harris's GML processing into a wiki page on Aggregate Model Systems in general.

**Pull request merged**
