### PR TITLE
Resolving Issue 57 - Clean up TOC and Headings

### PR DESCRIPTION
**Pull request by esilvia**
Generally this issue rearranges the source code divisions in a way that makes a lot more sense to me and seems much more sustainable long term, closing #57 .

The TOC is also more usable now with less clutter.

There are only two changes in the contents:

- I added a paragraph at the end of the Legacy section about VLRs vs EVLRs in a LAS 1.2-compatible file. This was copied from the EVLR section. Change here: https://github.com/ASPRSorg/LAS/compare/issue-57?expand=1#diff-aec4b641b7e13586e49a389ff7a7f32a
- I also moved the paragraph on the same topic from the Defined VLRs sections to the EVLRs section: https://github.com/ASPRSorg/LAS/compare/issue-57?expand=1#diff-40401c8091e819ee43576709a318cc2c

All other changes are heading changes, a typo correction, and shuffling source.

### CODE REVIEW

**Comment by esilvia** [comment]
Sorry, can you clarify what you mean? You mean like a summary of all changes from R13 to R14 in the spec itself?

**Comment by esilvia** [comment]
Oh crap. I just realized I'm trying to merge into the master branch instead of the draft branch, which is what I intended. That merge from draft-R14 is supposed to be the final review, which is separate. Sorry about that.

**Comment by hobu** [comment]
Section 1.1.2 states:

> R14 - Aesthetic changes from migration to GitHub

but R14 is a bit more than that. It needs some more description of what has happened.

**Comment by esilvia** [comment]
Thanks for catching that @hobu . I've attempted to update that changelog summary in each of the appropriate issue branches. Can you take a quick look at §1.1.2 and make sure it captures things succinctly? You know how wordy I can get...

https://s3.amazonaws.com/asprs-las/LAS-specification-35a612548879e1fdb5f361d55217af585209b641.pdf

**Comment by hobu** [comment]
I had @abellgithub, who's implemented a number of LAS things for [PDAL](https://pdal.io) skim the document. He stated that he'd like to see the changeset at the very top of the document – even in front of the Introduction – so he could clearly see what might have changed. I think you should switch the revision history section with the LAS 1.4 Additions section so it is front-and-center.

Your R14 revision language looks fine, but I would add real links to the GitHub issues to provide people convenience to go look at stuff for themselves.

**Pull request merged**
