### PR TITLE
Publish LAS 1.4 R14

### PR DESCRIPTION
**Pull request by esilvia**
LAS 1.4 R14 is ready for final comment before publication. Please post any comments on this thread and we'll do our best to address your feedback promptly.

Here's a summary of the changes with respect to R13, the current version (issue numbers included):

### Noteworthy changes:

- Additional standard classifications (19, 20, 21, 22) (#11, #26)
- Deprecated "tuple" and "triple" Extra Byte data types (#1)
- Clarified Full Waveform descriptions and added wiki (#9)
- Added language to support technologies other than conventional linear-mode lidar scanners (#35)

### Clarification or usability improvements:

- Aesthetic changes from GitHub migration
- Capitalization & typo corrections.
- Updated ASPRS contact information (#30)
- Added OGC endorsement (#31)
- Added minimum PDRF sizes to attribute tables (#47)
- Added hyperlinked Table of Contents and section numbers (#27, #49)
- Some section reorganization... divided VLR chapter into §3 and §4, expanded Legacy Compatibility sections (§2.1, §2.7.1), swapped change log order, and rearranged Extra Bytes VLR description.
- Changed type of ExtraByte min/max from `anytype` to `double`, which was the original intent. (#4)
    - Edit: Change redacted as discussed in the comments below. Instead, clarified that ExtraByte min/max should be in the raw data's format.
- Clarified that Legacy Point Counts should be zero if using non-legacy PDRFs (#12)
- PDRF 9 now correctly requires Scanner Channel like the other PDRFs (#29)
- Clarified origin date/time for Adjusted Standard GPS Time (#40)
- Clarified null-termination of fixed-length `char` arrays, especially VLR Description (#46)
- Clarified relationship between FileSourceID and PointSourceID (#59)
- Added wiki link for Project ID examples (#38)
- Added internal hyperlinks for better navigation (#28)

In accordance with the requirements for a Revision without incrementing the Version Number, there are no substantive changes that significantly impact the interpretation of the LAS format itself. 

PDF here: https://s3.amazonaws.com/asprs-las/LAS-specification-5ae7567ae98f953674c09b078596f72e0a08a223.pdf

Line by line comparisons: https://github.com/ASPRSorg/LAS/pull/76/files

### CODE REVIEW

**Comment by esilvia** [comment]
Line by line changes are here:
https://github.com/ASPRSorg/LAS/pull/76/files

**Comment by rapidlasso** [comment]
Turns out FUGRO implemented the triples in the Extra Bytes.

**Comment by rapidlasso** [comment]
For the "extra bytes" scale factor and offset. Should we state that the scale factor (if not used) should be set to 1.0 and that the offset (if not used) should be set to 0.0. I came across a data set that left the scale factor at zero and merely indicated in the 'options' that the scale factor was not set. This broke my code that always multiplied. Having a default value of 1.0 may safe future implementation from having that bug.

**Comment by esilvia** [comment]
The spec states in its current form that unused scale, offset, and nodata values should be zero if unused as indicated in the options field, which it sounds like is the case for your sample dataset. Since I don't see any ambiguity in its current form, I'm not sure that I can or should change that in a revision. Do you feel differently @rapidlasso ?

**Comment by rapidlasso** [comment]
Not strongly. But the best "zero" for a scale factor is a value of "1.0". It was just a poor decision / oversight when I wrote that part of the "Extra Bytes" specification back then and I wish I had formulated it like that.

**Comment by manfred-brands** [comment]
If we do want to simplify, then in that case one could deprecate the flags for offset/scale factor. They are always there and set to 0.0/1.0 as default. We should not have both a flag that indicates not to use them and a default value for those that ignore the flag.

**Comment by rapidlasso** [comment]
Here I strongly disagree. That would really change the specification as this also affects **used** scale factors (that may no longer get used because the flag is zero). My suggested change only affects the zero setting of **unused** scale factors.

**Comment by esilvia** [comment]
I've chewed on this for a bit and I think it's best to keep the scale defaulting to zero. When we implement a "Compact Extra Bytes" VLR then I think we should take this into consideration.

**Comment by esilvia** [comment]
Per a discussion on #1 regarding #4, I'm leaving this PR open for another day or two to ensure that we have consensus on R14. Thus far I believe we're clear to proceed with publication.

**Comment by rapidlasso** [comment]
The change from raw anytype to scaled and offset double values for the min / max values will require LASlib (and maybe other implementations) to make functional changes. How are we supposed to know whether an existing LAS/LAZ file uses the old anytype convention that is currently valid versus the new double convention that is soon to be valid? Here are the current functions used in the LASlib and LASzip APIs for this:

https://github.com/LAStools/LAStools/blob/master/LASzip/src/lasattributer.hpp#L119
https://github.com/LAStools/LAStools/blob/master/LASzip/src/lasattributer.hpp#L132
https://github.com/LAStools/LAStools/blob/master/LASzip/src/lasattributer.hpp#L277

**Comment by manfred-brands** [comment]
@rapidlasso comments repeat what I had previously said at [#1](https://github.com/ASPRSorg/LAS/issues/1#issuecomment-458355933)

No matter the intention, the R14 changes the type of the min/max fields from R13 without anywhere an indication in the file that it is a different version. CARIS stores min/max values as the field type. LASLib interprets them as such as well.

**Comment by rapidlasso** [comment]
CARIS stores min max doubles or min max anytype? I don't think LASlib / LAStools actually use those values anywhere at the moment.

**Comment by manfred-brands** [comment]
anytype:

Value interpreted as anytype:
Beam (UInt32) MinimumValue=1 MaximumValue=512 NoDataValue=4294967295 
Profile (UInt32) MinimumValue=1 MaximumValue=576 NoDataValue=4294967295 

Values interpreted as double:
Beam (UInt32) MinimumValue=4.94065645841247E-324 MaximumValue=2.52961610670718E-321 NoDataValue=4294967295
Profile (UInt32) MinimumValue=4.94065645841247E-324 MaximumValue=2.84581812004558E-321 NoDataValue=4294967295

**Comment by manfred-brands** [comment]
@rapidlasso some lasreader code is calling set_min/max and update_min/max. (_ply/_qfit/_txt). In the current version it is calling lasattributer.cast which converts the stored value to anytype.

**Comment by rapidlasso** [comment]
Yes. LASlib / LASzip can set anytype min/max values when writing. But I have no tool that uses the written values for any post processing. So I would currently not notice when these values are broken.

**Comment by esilvia** [comment]
You're right. A revision shouldn't change the field type regardless of intent. I'll revert #4 for R14 and defer it to 1.5.

**Comment by esilvia** [comment]
Now that the ExtraByte min/max objection has been resolved, this is the last call for comments before LAS 1.4 R14 gets released. If I receive no more objections, I'll merge the pull request, remove the DRAFT tags, and send the PDF to ASPRS for publication.

**Pull request merged**
