### PR TITLE
Publish LAS 1.4 R15

### PR DESCRIPTION
**Pull request by esilvia**
LAS 1.4 R15 is ready for final comment before publication. Please post any comments on this thread and we'll do our best to address your feedback promptly.

Here's a summary of the changes in this revision, which is intended to be an errata update for mistakes in the R14 conversion:

- Fixed unintended reordering of Min/Max XYZ in LAS Header (#79).
- Added missing Scanner Channel field in note about PDRF6-10 bit-field (#80).
- Minor editorial & punctuation corrections (#78).

Full Issues list: https://github.com/ASPRSorg/LAS/milestone/4?closed=1

In accordance with the requirements for a Revision that does not increment the Version Number, there are no substantive changes that significantly impact the interpretation of the LAS format itself, except the ones that correct unintended changes in R14.

---

Draft PDF available for review here: https://s3.amazonaws.com/asprs-las/LAS-specification-be273817a3f25badff6b052a3b0b61976f050ca5.pdf

Line-by-line changes available here: https://github.com/ASPRSorg/LAS/pull/83/files

### CODE REVIEW

**Comment by esilvia** [comment]
I expect the announcement to go out in the ASPRS Newsletter on Wednesday 6/19. Thus this will be closed for comment on 7/3/2019 to meeting the requirement for a 2-week public comment period.

**Comment by esilvia** [comment]
@milenajaniec sent me another round of minor editorial changes offline that I just incorporated in the latest commit to draft-15. They all fall under the existing changelog, so nothing really worth mentioning.

Draft PDF: https://s3.amazonaws.com/asprs-las/LAS-specification-ec6d48ddee064213f04a4b1a3c4fabb6d80fd91b.pdf
Line-by-line changes: https://github.com/ASPRSorg/LAS/pull/83/files

**Review by rapidlasso — COMMENTED** [review]
Looks fine to me. But I was also expecting the clarified description of the GPS time stamps in this revision.

**Comment by esilvia** [comment]
@rapidlasso  Thanks Martin. I didn't get confirmation that my wording was to your satisfaction so I deferred it to R16 rather than delay R15.

**Pull request merged**
